-- SQLite
CREATE TABLE users (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    ward VARCHAR(255) NOT NULL,
    polling_unit VARCHAR(255) NOT NULL,
    pvc_number VARCHAR(255) NOT NULL UNIQUE,
    phone_number VARCHAR(255) NOT NULL UNIQUE,
    address VARCHAR(500) NOT NULL,
    role VARCHAR(25) NOT NULL DEFAULT 'user',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)